export { default as useCreateSchool } from "./useCreateSchool";
export { default as useSchools } from "./useSchools";
export { default as useUpdateShool } from "./useUpdateSchool";
export { default as useCreateStudent } from "./useCreateStudent";
export { default as useUpdateStudent } from "./useUpdateStudent";
export { default as useStudents } from "./useStudents";
export { default as useOwners } from "./useOwners";
export { default as useCreateOwner } from "./useCreateOwner";
export { default as useRemoveOwner } from "./useRemoveOwner";
