import type { FormAdminSchool } from "./types";

export const adminSchoolsMock: Array<FormAdminSchool> = [
  {
    id: "1",
    name: "Harvard",
    website: "https://www.google.de/",
    img: "images/harvard.webp",
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "2",
    name: "Stanford",
    website: "https://www.google.de/",
    img: "images/harvard.webp",
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "3",
    name: "MIT",
    website: "https://www.google.de/",
    img: "images/harvard.webp",
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "4",
    name: "Harvard",
    website: "https://www.google.de/",
    img: "images/harvard.webp",
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "5",
    name: "Stanford",
    website: "https://www.google.de/",
    img: "images/harvard.webp",
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "6",
    name: "MIT",
    website: "https://www.google.de/",
    img: "images/harvard.webp",
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "7",
    name: "Harvard",
    website: "https://www.google.de/",
    img: "images/harvard.webp",
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "8",
    name: "Stanford",
    website: "https://www.google.de/",
    img: "images/harvard.webp",
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "9",
    name: "MIT",
    website: "https://www.google.de/",
    img: "images/harvard.webp",
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "10",
    name: "Harvard",
    website: "https://www.google.de/",
    img: "images/harvard.webp",
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "11",
    name: "Stanford",
    website: "https://www.google.de/",
    img: "images/harvard.webp",
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
];
