import { Principal } from "@dfinity/principal";
import type {
  FormAdminPrincipal,
  FormAdminSchool,
  FormAdminStudent,
} from "./types";
import { parseDate } from "@internationalized/date";

export const adminSchoolsMock: Array<FormAdminSchool> = [
  {
    id: "1",
    name: "Harvard",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "2",
    name: "Stanford",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "3",
    name: "MIT",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "4",
    name: "Harvard",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "5",
    name: "Stanford",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "6",
    name: "MIT",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "7",
    name: "Harvard",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "8",
    name: "Stanford",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "9",
    name: "MIT",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "10",
    name: "Harvard",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "11",
    name: "Stanford",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "12",
    name: "Stanford",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "13",
    name: "Stanford",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
  {
    id: "14",
    name: "Stanford",
    website: "https://www.google.de/",
    images: [],
    active: true,
    location: "Massachusetts Hall, Cambridge, MA 02138, United States",
    numberOfStudents: 100,
  },
];

export const adminStudentsMock: Array<FormAdminStudent> = [
  {
    id: "1",
    firstName: "Tonya",
    lastName: "Johnston",
    dateOfBirth: parseDate("2005-07-30"),
    grade: "D",
    images: [],
    active: true,
  },
  {
    id: "2",
    firstName: "Kelli",
    lastName: "Diaz",
    dateOfBirth: parseDate("2002-01-03"),
    grade: "E",
    images: [],
    active: true,
  },
  {
    id: "3",
    firstName: "Charles",
    lastName: "Smith",
    dateOfBirth: parseDate("2005-05-22"),
    grade: "A",
    images: [],
    active: true,
  },
  {
    id: "4",
    firstName: "Mark",
    lastName: "Hill",
    dateOfBirth: parseDate("2002-05-23"),
    grade: "C",
    images: [],
    active: true,
  },
  {
    id: "5",
    firstName: "Lisa",
    lastName: "Walker",
    dateOfBirth: parseDate("2004-09-14"),
    grade: "C",
    images: [],
    active: true,
  },
  {
    id: "6",
    firstName: "Sarah",
    lastName: "Nelson",
    dateOfBirth: parseDate("2002-12-21"),
    grade: "D",
    images: [],
    active: true,
  },
  {
    id: "7",
    firstName: "Stephen",
    lastName: "Gamble",
    dateOfBirth: parseDate("2002-08-24"),
    grade: "E",
    images: [],
    active: true,
  },
  {
    id: "8",
    firstName: "Hayley",
    lastName: "Sharp",
    dateOfBirth: parseDate("2001-03-31"),
    grade: "B",
    images: [],
    active: true,
  },
  {
    id: "9",
    firstName: "Brian",
    lastName: "Smith",
    dateOfBirth: parseDate("2002-09-10"),
    grade: "C",
    images: [],
    active: true,
  },
  {
    id: "10",
    firstName: "Edward",
    lastName: "Brown",
    dateOfBirth: parseDate("2003-01-22"),
    grade: "D",
    images: [],
    active: true,
  },
  {
    id: "11",
    firstName: "Crystal",
    lastName: "Boone",
    dateOfBirth: parseDate("2005-04-24"),
    grade: "B",
    images: [],
    active: true,
  },
  {
    id: "12",
    firstName: "James",
    lastName: "Brown",
    dateOfBirth: parseDate("2001-03-08"),
    grade: "A",
    images: [],
    active: true,
  },
  {
    id: "13",
    firstName: "Bonnie",
    lastName: "Torres",
    dateOfBirth: parseDate("2002-02-16"),
    grade: "C",
    images: [],
    active: true,
  },
  {
    id: "14",
    firstName: "John",
    lastName: "Freeman",
    dateOfBirth: parseDate("2005-07-18"),
    grade: "E",
    images: [],
    active: true,
  },
  {
    id: "15",
    firstName: "Michael",
    lastName: "Miller",
    dateOfBirth: parseDate("2005-06-22"),
    grade: "B",
    images: [],
    active: true,
  },
  {
    id: "16",
    firstName: "Kimberly",
    lastName: "Lewis",
    dateOfBirth: parseDate("2002-08-12"),
    grade: "B",
    images: [],
    active: true,
  },
  {
    id: "17",
    firstName: "Katherine",
    lastName: "Martin",
    dateOfBirth: parseDate("2004-11-15"),
    grade: "D",
    images: [],
    active: true,
  },
  {
    id: "18",
    firstName: "Christopher",
    lastName: "Freeman",
    dateOfBirth: parseDate("2001-12-04"),
    grade: "A",
    images: [],
    active: true,
  },
  {
    id: "19",
    firstName: "Christopher",
    lastName: "Gilmore",
    dateOfBirth: parseDate("2002-05-04"),
    grade: "E",
    images: [],
    active: true,
  },
  {
    id: "20",
    firstName: "Johnny",
    lastName: "Pena",
    dateOfBirth: parseDate("2004-10-23"),
    grade: "B",
    images: [],
    active: true,
  },
  {
    id: "21",
    firstName: "Johnny",
    lastName: "Pena",
    dateOfBirth: parseDate("2004-10-23"),
    grade: "B",
    images: [],
    active: true,
  },
  {
    id: "22",
    firstName: "Johnny",
    lastName: "Pena",
    dateOfBirth: parseDate("2004-10-23"),
    grade: "B",
    images: [],
    active: true,
  },
];

export const principalMock: Array<FormAdminPrincipal> = [
  {
    id: "j6j3u-wljnz-g2tly-352iy-ny7ka-dzdkc-ycrun-wnr3d-fl63p-ofyxf-oae",
    principal: Principal.fromText(
      "j6j3u-wljnz-g2tly-352iy-ny7ka-dzdkc-ycrun-wnr3d-fl63p-ofyxf-oae"
    ),
  },
  {
    id: "uj2qy-jtqgc-f356u-y6a4u-ytehk-twomg-ozfmt-cvvwn-buhk3-2mu47-cae",
    principal: Principal.fromText(
      "uj2qy-jtqgc-f356u-y6a4u-ytehk-twomg-ozfmt-cvvwn-buhk3-2mu47-cae"
    ),
  },
  {
    id: "3gsl5-pfwlm-ev7u4-hfhr3-jvwhx-g2iwv-opmfc-sknds-2aor5-xx5nd-sqe",
    principal: Principal.fromText(
      "3gsl5-pfwlm-ev7u4-hfhr3-jvwhx-g2iwv-opmfc-sknds-2aor5-xx5nd-sqe"
    ),
  },
];
